# @name login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

###

# @name listSettlements
GET {{baseUrl}}/api/v1/settlements
?page=1
&pageSize=10
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name createSettlement
POST {{baseUrl}}/api/v1/settlements
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "name": "Postman settlement",
    "participantNames": [
        "Agata",
        "Blazej"
    ]
}

### 

# @name getSettlement
GET {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}


### 

# @name updateSettlement
PUT {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "name": "Updated settlement",
    "participants": [
        {
            "id": "{{getSettlement.response.body.participants[0].id}}",
            "nickname": "Updated Agata"
        },
        {
            "id": "{{getSettlement.response.body.participants[1].id}}",
            "nickname": "Updated Blazej"
        },
        {
            "nickname": "New participant"
        }
    ]
}

###

# @name deleteSettlement
DELETE {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name deleteSettlementWithIfMatchHeader
DELETE {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}
Authorization: Bearer {{login.response.body.accessToken}}
If-Match: {{getSettlement.response.headers.ETag}}

### 

# @name joinSettlement
POST {{baseUrl}}/api/v1/settlements/join
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
    "inviteCode": "{{getSettlement.response.body.inviteCode}}"
}

###

# @name leaveSettlement
POST {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}/leave
Authorization: Bearer {{login.response.body.accessToken}}


###

# @name claimParticipant
PATCH {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}/participants/{{getSettlement.response.body.participants[0].id}}/claim
Authorization: Bearer {{login.response.body.accessToken}}

### 

# @name getExpenses
GET {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}/expenses
Authorization: Bearer {{login.response.body.accessToken}}

###

# @name reimbursement
GET {{baseUrl}}/api/v1/settlements/{{createSettlement.response.body.$}}/reimbursement
Authorization: Bearer {{login.response.body.accessToken}}