# @name register
POST {{baseUrl}}/api/v1/users/register
Content-Type: application/json

{
    "email": "testa@example.com",
    "password": "password",
    "nickname": "Tomasqz"
}

### 

# @name login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json

{
    "email": "testa@example.com",
    "password": "password"
}

###

# @name me
GET {{baseUrl}}/api/v1/users/me
Authorization: Bearer {{login.response.body.accessToken}}
